### ISSUE TITLE
Generar documentación

### ISSUE THREAD

**Issue by Obsinqsob01** [AndrusGerman/GoAssembly#1]
Los ejemplos que pones en el README.md son buenos, pero **creo que le haria falta documentar cada función del paquete** para poder extender su uso.

PD: Me gustó tu trabajo :smile: :+1: 
PD2: Sería genial que abrieras una sección de issues y una guia de contribuciones para ayudarte mejor en el proyecto!

**Comment by AndrusGerman** [comment]
Claro con mucho Gusto , Ya que antes estaba moviendo muchas cosas no queria dedicarme de lleno a la documentación. Ya Estoy trabajando en ella
